---
title: "session8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(dplyr)
library(tidyr)
library(readr)
```


## Data sources

### Read in the data

```{r}
catch_original <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

## Clean and reshape the data

```{r}
catch_data <- catch_original %>%
  select(-All, -notesRegCode)
```

```{r}
catch_clean<- catch_data %>%
  mutate(Chinook=as.numeric(Chinook)) 
```

### Remove unnecessary columns

### Check column typing

```{r}
catch_clean <- catch_data %>%
  mutate(Chinook = ifelse(Chinook == "I", 1, Chinook))%>%
  mutate(Chinook = as.numeric(Chinook))
```


### Reshape data

```{r}
catch_long <- catch_clean %>% 
  pivot_longer(-c(Region, Year), names_to = "species", values_to ="catch")
```

```{r}
catch_wide <- catch_long %>%
  pivot_wider(names_from = "species", values_from = "catch")
```

```{r}
catch_long <- catch_long %>%
  rename(catch_thousands = catch)
```

```{r}
catch_long <- catch_long %>%
  mutate(catch = catch_thousands * 1000) %>%
  select(-catch_thousands)
```

```{r}
mean_region <- catch_long %>% 
  group_by(Region) %>%
  summarise(catch_mean = mean(catch)) %>%
  arrange(desc(catch_mean))
```
```{r}
n_region<- catch_long %>%
  group_by(Region) %>%
  summarise(n = n())
```


```{r}
SSE_catch <- catch_long %>%
  filter(Region == "SSE")
```

## Join to Regions dataset

```{r}
region_defs <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1") %>%
  select(code, mgmtArea)
```

```{r}
catch_joined <- left_join(catch_long, region_defs, by = c("Region" = "code"))
```

```{r}
sites_df <- data.frame(site = c("HAW-101",
                                "HAW-103",
                                "OAH-320",
                                "OAH-219",
                                "MAI-039"))

sites_df %>% 
  separate(site, c("island", "site_number"), "-")
```


```{r}
dates_df <- data.frame(year = c("1930",
                                "1930",
                                "1930"),
                       month = c("12",
                                "12",
                                "12"),
                       day = c("14",
                               "15",
                               "16"))
dates_df %>% 
  unite(date, year, month, day, sep = "-")
```







